import java.util.Random;
import java.util.ArrayList;
public class Event {
  public String textE;
    public int [] foodE = {25, 0, 10, 0, 0, 10 ,0 , 0, 0, 0, -20, 0, -10, 0, 25, 0, 10, 0, 0, -10, 0, 0, 0, 0, -20, 0, -10, 0, 25, 0, 10, 0, 0, -10, 0, 0, 0, -1, -20, 0, -10, 0, 15, 0, 10, 0, 0, 10, 0, 0, 0, 0, -20, 0, -10, 0};
    public int [] peopleE = {0, 0, 0, 5, 0, 0, 0, -5, 0, -1, -5, 0, 0, 0, 0, 0, 0, 5, 0, 5, 0, -10, 0, -1, -5, 0, 0, 0, 0, 0, 0, 5, 0, 5, 0, -5, 0, -1, -5, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, -10, 0, -1, -5, 0, 0, 0};
    public int [] housingE = {0, 0, 0, 5, 0, -5, 0, -15, 0, -1, 0, -20, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, -1, 0, -20, 0, 0, 0, 0, 0, 5, 0, 0, 0, -15, 0, 0, 0, -20, 0, 0, 0, 0, 0, 5, 0, -5, 0, 0, 0, -1, 0, -20, 0, 0};
    public int [] resourceAdd = {4, 3, 6, 0, 2, 0, 3, 1, 3, 0, 0, 0, 0, 0, 0, 3, 6, 0, 2, 0, 3, 7, 3, 0, 0, 0, 0, 0, 4, 3, 6, 0, 2, 0, 2, 1, 3, 0, 0, 0, 0, 0, 4, 3, 6, 0, 5, 0, 2, 8, 5, 0, 0, 0, 0, 0, };
    public int [] resourceRemove = {0, 0, 0, 0, 4, 0, 2, 0, 7, 1, 0, 4, 6, 0, 0, 0, 0, 0, 3, 0, 2, 0, 1, 2, 0, 1, 6, 0, 0, 0, 0, 0, 4, 0, 1, 0, 8, 4, 0, 1, 6, 0, 0, 0, 0, 0, 1, 0, 7, 0, 3, 3, 0, 3, 6, 0};
  public void allEvents (int n) {
    switch (n) {
      case 0: textE = "Local pollinators fly by and make your soil fertile. You get 1 soil and " + foodE[n] + " food";
        break;
      case 1: textE = "A breeze carries a raincloud to your settlement, filling your rain barrels. You get 1 water.";
        break;
      case 2: textE = "A group of large mammals wander by your settlement. You get 1 game and " + foodE[n] + " food.";
        break;
      case 3: textE = "You come across an amicable group of strangers. You get " + peopleE[n] + " people and " + housingE[n] + " housing.";
        break;
      case 4: textE = "A field of saplings grows into a forest. You get 1 wood but get -1 soil.";
        break;
      case 5: textE = "You find a giant gingerbread house. You get " + foodE[n] + " food but get " + housingE[n] + " housing.";
        break;
      case 6: textE = "A rainstorm catches your settlement and lightning strikes a tree. You get 1 water but get -1 wood.";
        break;
      case 7: textE = "A bolder rolls into your settlement. You gain 1 stone but get " + housingE[n] + " housing and " + peopleE[n] + " people.";
        break;
      case 8: textE = "A river floods a mine. You gain 1 water but get -1 iron.";
        break;
      case 9: textE = "A small hill gives way to a large hole under a house. You get -1 stone, " + peopleE[n] + " person and " + housingE[n] + " housing.";
        break;
      case 10: textE = "You come across a malicious group of strangers. You get " + peopleE[n] + " people and " + foodE[n] + " food.";
        break;
      case 11: textE = "A tornado ransacks your settlement, ruining everything. You get " + housingE[n] + " housing and -1 soil.";
        break;
      case 12: textE = "Predators eat your livestock over night. You get -1 game and " + foodE[n] + " food.";
        break;
      case 13: textE = "Your settlement is flooded. You lose all people without housing.";
        break;
      case 14: textE = "The summer sun warms the earth. You get 1 soil and " + foodE[n] + " food";
        break;
      case 15: textE = "A storm appears, but is gone even before the first thunderclap, filling your rain barrels. You get 1 water.";
        break;
      case 16: textE = "A group of large mammals wander by your settlement. You get 1 game and " + foodE[n] + " food.";
        break;
      case 17: textE = "You open a medical clinic on the outskirts of your settlement. You get " + peopleE[n] + " people and " + housingE[n] + " housing.";
        break;
      case 18: textE = "You find gold at the bottom of a river. You get 1 gold but get -1 water.";
        break;
      case 19: textE = "You come across a hungry group of strangers. You get " + peopleE[n] + " people but get " + foodE[n] + " food.";
        break;
      case 20: textE = "A brisk wind blows over a tree, daming a river and creating a pond. You get 1 water but get -1 wood.";
        break;
      case 21: textE = "An exploration team goes missing, but they found iron. You gain 1 iron but get " + peopleE[n] + " people.";
        break;
      case 22: textE = "A cliff crumbles into the sea. You gain 1 water but get -1 stone.";
        break;
      case 23: textE = "A tree falls on to a house. You get -1 wood, " + peopleE[n] + " person and " + housingE[n] + " housing.";
        break;
      case 24: textE = "You come across a malicious group of strangers. You get " + peopleE[n] + " people and " + foodE[n] + " food.";
        break;
      case 25: textE = "A earthquake ransacks your settlement, ruining everything. You get " + housingE[n] + " housing and -1 stone.";
        break;
      case 26: textE = "Predators eat your livestock over night. You get -1 game and " + foodE[n] + " food.";
        break;
      case 27: textE = "Your settlement is struck by a sudden heat wave. You lose all people without housing.";
        break;
      case 28: textE = "Leaves fall to the groud and decompose, making your soil fertile. You get 1 soil and " + foodE[n] + " food";
        break;
      case 29: textE = "You discover a cold spring far off in the woods. You get 1 water.";
        break;
      case 30: textE = "A group of large mammals wander by your settlement. You get 1 game and " + foodE[n] + " food.";
        break;
      case 31: textE = "You come across an amicable group of strangers. You get " + peopleE[n] + " people and " + housingE[n] + " housing.";
        break;
      case 32: textE = "A tree tumbles into your wood pile, ripping up the dirt at its roots. You get 1 wood but get -1 soil.";
        break;
      case 33: textE = "You come across a hungry group of strangers. You get " + peopleE[n] + " people but get " + foodE[n] + " food.";
        break;
      case 34: textE = "A giant tree grows on top of a bolder, its roots crushing the rock. You get 1 wood but get -1 stone.";
        break;
      case 35: textE = "A cliff crumbles over your settlement. You gain 1 stone but get " + housingE[n] + " housing and " + peopleE[n] + " people.";
        break;
      case 36: textE = "A river floods a mine. You gain 1 water but get -1 gold.";
        break;
      case 37: textE = "Lose soil covered by leaves falls away under foot. You get -1 soil, " + peopleE[n] + " person and " + foodE[n] + " food.";
        break;
      case 38: textE = "You come across a small pack of ferocious canines. You get " + peopleE[n] + " people and " + foodE[n] + " food.";
        break;
      case 39: textE = "A hurricane ransacks your settlement, ruining everything. You get " + housingE[n] + " housing and -1 wood.";
        break;
      case 40: textE = "The fence holding your livestock rots and they run away. You get -1 game and " + foodE[n] + " food.";
        break;
      case 41: textE = "Your settlement is hit by a hailstorm. You lose all people without housing.";
        break;
      case 42: textE = "Moisture from melted snow seeps into the ground. You get 1 soil and " + foodE[n] + " food";
        break;
      case 43: textE = "You melt recently fallen snow. You get 1 water.";
        break;
      case 44: textE = "A group of large mammals wander by your settlement. You get 1 game and " + foodE[n] + " food.";
        break;
      case 45: textE = "You open a medical clinic on the outskirts of your settlement. You get " + peopleE[n] + " people and " + housingE[n] + " housing.";
        break;
      case 46: textE = "You find mineral in a cliff. You get 1 mineral but get -1 stone.";
        break;
      case 47: textE = "You find a giant gingerbread house. You get " + foodE[n] + " food but get " + housingE[n] + " housing.";
        break;
      case 48: textE = "A snow laden tree falls, making a mine collapse. You get 1 wood but get -1 iron.";
        break;
      case 49: textE = "An exploration team goes missing, but they found gold. You gain 1 gold but get " + peopleE[n] + " people.";
        break;
      case 50: textE = "Cutting a chunk of ice out of a river reveals mineral. You gain 1 mineral but get -1 water.";
        break;
      case 51: textE = "A large amount of snow crushes a house. You get -1 water, " + peopleE[n] + " person and " + housingE[n] + " housing.";
        break;
      case 52: textE = "You come across a small pack of ferocious canines. You get " + peopleE[n] + " people and " + foodE[n] + " food.";
        break;
      case 53: textE = "A blizzard ransacks your settlement, ruining everything. You get " + housingE[n] + " housing and -1 water.";
        break;
      case 54: textE = "Your livestock freezes to death over night. You get -1 game and " + foodE[n] + " food.";
        break;
      case 55: textE = "Your settlement is struck by a sudden cold snap. You lose all people without housing.";
        break;
    }
  }
}